### ISSUE TITLE
ISHRemote Compilation failed on Visual Studio 2022

### ISSUE THREAD

**Issue by shrinidhijanaki** [RWS/ISHRemote#161]
error MSB3073: The command "pwsh -NonInteractive -command "Import-Module D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin/Debug/net48/Trisoft.ISHRemote.dll -Force;$cmdletsToExport=(Get-Module -Name Trisoft.ISHRemote).ExportedCommands.Keys;New-ModuleManifest -Path 'D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin/Debug/ISHRemote/ISHRemote.psd1' -FormatsToProcess 'ISHRemote.Format.ps1xml' -FunctionsToExport @('Get-IshAuxSessionState', 'New-IshAuxCompletionResult', 'Register-IshAuxParameterCompleter') -RootModule 'ISHRemote.psm1' -ModuleVersion '7.1.0' -Prerelease 'preview001' -Guid '0314ffdb-6083-4c4d-aa01-8bfaac51a7e4' -Author 'RWS Group for and on behalf of its affiliates and subsidiaries' -CompanyName 'RWS Group for and on behalf of its affiliates and subsidiaries' -Copyright 'Copyright (c) 2023 All Rights Reserved by the RWS Group for and on behalf of its affiliates and subsidiaries.' -Description 'Business automation module on top of Tridion Docs Content Manager (Knowledge Center Content Manager, LiveContent Architect, Trisoft InfoShare)' -PowerShellVersion '5.1' -ClrVersion '4.0' -DotNetFrameworkVersion '4.8' -LicenseUri 'https://github.com/rws/ISHRemote/blob/master/LICENSE.TXT' -ProjectUri 'https://github.com/rws/ISHRemote/' -CmdletsToExport @($cmdletsToExport)"" exited with code 9009.

Code is taken from the GitHub Repository master branch and compiling directly on the Windows 11 machine

Appreciate any one with addresses this issue or suggestions here, what is going wrong in compiling the code on Windows 11 with dotnet version 7.0+

**Comment by ivandelagemaat** [comment]
ISHRemote requires net48 and net6.0 frameworks for a successful compilation. Are both frameworks available on your Windows 11 machine?

**Comment by shrinidhijanaki** [comment]
yes both are available on windows 11. I verified both the versions using the below command

PS  Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" -Name Version

Version      : 4.8.04161
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
PSChildName  : Full
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry

PS  dotnet --version
7.0.304

**Comment by shrinidhijanaki** [comment]
here is the complete compilation output for reference
Build started...
1>------ Build started: Project: Trisoft.ISHRemote, Configuration: Debug Any CPU ------
Restored D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\Trisoft.ISHRemote.csproj (in 229 ms).
1>Trisoft.ISHRemote -> D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll
1>AssemblyPath: D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll, OutputHelpFilePath: D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll-Help.xml, TreatWarningsAsErrors False
1>GenerateHelp completed with exit code 'Success'
1>'pwsh' is not recognized as an internal or external command,
1>operable program or batch file.
1>D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\Trisoft.ISHRemote.csproj(96,2): error MSB3073: The command "pwsh -NonInteractive -command "Import-Module D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll -Force;$cmdletsToExport=(Get-Module -Name Trisoft.ISHRemote).ExportedCommands.Keys;New-ModuleManifest -Path 'D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\ISHRemote\ISHRemote.psd1' -FormatsToProcess 'ISHRemote.Format.ps1xml' -FunctionsToExport @('Get-IshAuxSessionState', 'New-IshAuxCompletionResult', 'Register-IshAuxParameterCompleter') -RootModule 'ISHRemote.psm1' -ModuleVersion '7.1.0' -Prerelease 'preview001' -Guid '0314ffdb-6083-4c4d-aa01-8bfaac51a7e4' -Author 'RWS Group for and on behalf of its affiliates and subsidiaries' -CompanyName 'RWS Group for and on behalf of its affiliates and subsidiaries' -Copyright 'Copyright (c) 2023 All Rights Reserved by the RWS Group for and on behalf of its affiliates and subsidiaries.' -Description 'Business automation module on top of Tridion Docs Content Manager (Knowledge Center Content Manager, LiveContent Architect, Trisoft InfoShare)' -PowerShellVersion '5.1' -ClrVersion '4.0' -DotNetFrameworkVersion '4.8' -LicenseUri 'https://github.com/rws/ISHRemote/blob/master/LICENSE.TXT' -ProjectUri 'https://github.com/rws/ISHRemote/' -CmdletsToExport @($cmdletsToExport)"" exited with code 9009.
1>Done building project "Trisoft.ISHRemote.csproj" -- FAILED.
1>Trisoft.ISHRemote -> D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net6.0\Trisoft.ISHRemote.dll
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 7:30 PM and took 12.946 seconds ==========

**Comment by shrinidhijanaki** [comment]
i could fix the owsh issue by updating the alias and proj file local to my system. now i see a difrferent problem 

Build started...
1>------ Build started: Project: Trisoft.ISHRemote, Configuration: Debug Any CPU ------
Restored D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\Trisoft.ISHRemote.csproj (in 499 ms).
1>Trisoft.ISHRemote -> D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll
1>AssemblyPath: D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll, OutputHelpFilePath: D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll-Help.xml, TreatWarningsAsErrors False
1>GenerateHelp completed with exit code 'Success'
1>Trisoft.ISHRemote -> D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net6.0\Trisoft.ISHRemote.dll
1>**New-ModuleManifest : A parameter cannot be found that matches parameter name 'Prerelease'.
1>At line:1 char:582
1>+ ... ootModule 'ISHRemote.psm1' -ModuleVersion '7.1.0' -Prerelease 'previe ...
1>+                                                       ~~~~~~~~~~~
1>    + CategoryInfo          : InvalidArgument: (:) [New-ModuleManifest], ParameterBindingException
1>    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.New**ModuleManifestCommand
1>
1>D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\Trisoft.ISHRemote.csproj(96,2): error MSB3073: The command "powershell.exe -NonInteractive -command "Import-Module D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\net48\Trisoft.ISHRemote.dll -Force;$cmdletsToExport=(Get-Module -Name Trisoft.ISHRemote).ExportedCommands.Keys;New-ModuleManifest -Path 'D:\Cops-Projects\Repositories\GitHub\ISHRemote-TD15\Source\ISHRemote\Trisoft.ISHRemote\bin\Debug\ISHRemote\ISHRemote.psd1' -FormatsToProcess 'ISHRemote.Format.ps1xml' -FunctionsToExport @('Get-IshAuxSessionState', 'New-IshAuxCompletionResult', 'Register-IshAuxParameterCompleter') -RootModule 'ISHRemote.psm1' -ModuleVersion '7.1.0' -Prerelease 'preview001' -Guid '0314ffdb-6083-4c4d-aa01-8bfaac51a7e4' -Author 'RWS Group for and on behalf of its affiliates and subsidiaries' -CompanyName 'RWS Group for and on behalf of its affiliates and subsidiaries' -Copyright 'Copyright (c) 2023 All Rights Reserved by the RWS Group for and on behalf of its affiliates and subsidiaries.' -Description 'Business automation module on top of Tridion Docs Content Manager (Knowledge Center Content Manager, LiveContent Architect, Trisoft InfoShare)' -PowerShellVersion '5.1' -ClrVersion '4.0' -DotNetFrameworkVersion '4.8' -LicenseUri 'https://github.com/rws/ISHRemote/blob/master/LICENSE.TXT' -ProjectUri 'https://github.com/rws/ISHRemote/' -CmdletsToExport @($cmdletsToExport)"" exited with code 1.
1>Done building project "Trisoft.ISHRemote.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 7:55 PM and took 11.809 seconds ==========

**Comment by shrinidhijanaki** [comment]
can anybody guide me here how to fix this manifest issue?

**Comment by shrinidhijanaki** [comment]
which is the correct version for which i can compile the code to Tridion Docs 15. We need to compile and integrate into our custom tools. This is somewhat like a blocker.

**Comment by ivandelagemaat** [comment]
Did you install PowerShell Core? https://github.com/PowerShell/PowerShell
You don't have to compile ISHRemote in order to use it, you can use the PowerShell Gallery to install ISHRemote https://www.powershellgallery.com/packages/ISHRemote/7.0.0

**Comment by shrinidhijanaki** [comment]
Thanks for your inputs. I found that Powershell core was not installed on my system. Installing PS Core resolved the problem
Also i have one query, we are using ISHRemote Project internally in several other C# console projects by using ISHRemote.dll library. My Query is do we need to have PS Core installed on the system where we are deploying the ISHRemote library?

> Did you install PowerShell Core? https://github.com/PowerShell/PowerShell You don't have to compile ISHRemote in order to use it, you can use the PowerShell Gallery to install ISHRemote https://www.powershellgallery.com/packages/ISHRemote/7.0.0

**Comment by ivandelagemaat** [comment]
I don't know how you are using the ISHRemote library in your project but probably you don't need PS Core when deploying your project on an other system. ISHRemote can be used with PowerShell and PowerShell Core and therefor it is compiled twice, one for the full framework net4.8 and once for .NET Core net6.0. Pick the right one for your project.

**Comment by shrinidhijanaki** [comment]
Team,
I would like to set the context here first here before getting in deeper.

Objective:
Write a Simple C# wrapper to execute the ISHRemote CmdLets.

Steps:
1. i downloaded the bundle as is to verify the bundles by writing a sample
c# application to just establish Session without installation of ishremote
on the system, i started getting error "New-IshSession cmdLet not Found"
Error.
2. Then i installed 7.0.0 version of IshRemote on Windows 11 OS. Then
retried the application.
3. This time started getting the error differently saying "IshRemote"
Module is not imported. I am stuck here. Reason is i am able to run the
commands on powershell editor after following the instructions mentioned in
the mail trail below. But am still not able to involve New-IshSession
command let in c# application.
4. Not Sure what exactly the problem is. I noticed that the issue is
happening on windows 11 OS. I also verified with

Still i could not fix the issue.
I have set the environments as mentioned below mail trail.

Any suggestions or idea would be really helpful.
Thanks & Regards
Shrinidhi

**Comment by ddemeyer** [comment]
Hi Shrinidhi ... So ISHRemote is C# code that is delivered as a .NET Assembly complying with the PowerShell library standard. In turn the assembly library can be loaded (~ `Import-Module`) in a Windows PowerShell.exe or Pwsh.exe process so you can run its cmdlets (~ `New-IshSession`).

A. So based on the above you are wrapping the PowerShell executable again in a new C# program. Something along the lines of https://stackoverflow.com/questions/13251076/calling-powershell-from-c-sharp ? I'm still puzzled what business problem you are trying to solve.

B. Either you scenario above or what I will describe next is for me _not_ the core purpose of ISHRemote, it is an edge case ... it is however open source so in a way you can have multiple attempts for whatever you desire :) Why not load the `Trisoft.ISHRemote.dll` directly into your C# project and run the necessary classes (~ ÌshSession`) yourself. In the end it is open source so you can have a look what is happening inside `New-IshSession`.

Best wishes,
Dave

**Comment by shrinidhijanaki** [comment]
Hi ddmeyer,

Thanks for your response.

My purpose of using C# is to write a ISHRemote Wrapper for certain common
functionalities for our daily and regular work for
1. Establishing Connection to Tridion 14 SP4 and getting prepared
with IShRemote Wrapper for Tridion 15.
2. invoke the API within a wrapper using IshRemote Modules  and solve our
BP.

I could fix the problem
1. By changing the platform from ARM64 to _x64 and adding the references of
Trisoft.IshRemote dll library from Modulepath directly. (Still not sure why
the Any CPU) platform settings doesn't work in visual studio.
2. I could run the wrapper in C# using ScriptBlock and IShRemote Modules
and was able to get the Results successfully.

Thanks For your inputs and response.

**Comment by ddemeyer** [comment]
Thanks for closing the loop, appreciated! Just as a reminder...
* You are currently on the released ISHRemote v7.0 with release notes near https://github.com/RWS/ISHRemote/blob/master/Doc/ReleaseNotes-ISHRemote-0.7.md
* There is a work-in-progress branch to introduce Modern Authentication - a big feature of Tridion Docs 15/15.0.0 - in an upcoming ISHRemote v8.0 ... the draft release notes are in a branch on https://github.com/RWS/ISHRemote/blob/feature/152-refactor-InfoShareWcfConnection/Doc/ReleaseNotes-ISHRemote-8.0.md

**Comment by shrinidhijanaki** [comment]
Cool, thanks for the heads up!

When is the new version release of ishremote  expected for tridion 15?

As we are migrating to tridion 15 in the coming month, I would like to know
can we use the latest version a at that time by October 15 2023?

Appreciate your help
