### ISSUE TITLE
Extend Remove-IshPublicationOutput to always execute -Force parameter starting release 15.1/Alf1 so content object are deleted in full

### ISSUE THREAD

**Issue by BlackPower** [RWS/ISHRemote#162]
The Remove-IshPublicationOutput cmdlet fails with the next error:
```
FAIL  [-102] The publication MYGUID-20230818054512-911 does not exist. [ce:"MYGUID-20230818054512-911"] [102;ObjectNotFound]
[ERROR] FAIL Test.PublicationOutput25-UnreleaseScenario ([-102] The publication MYGUID-20230818054512-911 does not exist. [ce:"MYGUID-20230818054512-911"] [102;ObjectNotFound])
```
on Tridion Docs 15.1 with the "-Force" parameter as the server logic was changed.

Starting from Tridion Docs 15.1 the server automatically removes Publication (logical level) if the last version is deleted. So, the cmdlet should not delete the logical level for Tridion Docs 15.1.

TODO:
* Change the cmdlet logic to not delete the logical level for Tridion Docs 15.1. Leave the previous behavior for Tridion Docs 15 version
* Add the Pester test

**Comment by ddemeyer** [comment]
Similar to #138
