### ISSUE TITLE
IShSession.IshTypeFieldDefinition type ISHBackgroundTask is enhanced to support dynamic result coming from API Settings.RetrieveFieldSetupByIshType in 15.1/Alf1

### ISSUE THREAD

**Issue by ArianArt** [RWS/ISHRemote#177]
Starting from Docs 15.1/Alf1 the cmdlet Get-IshTypeFieldDefinition gets the field information for type ISHBackgroundTask from Tridion Docs Settings 2.5 RetrieveFieldSetupByIshType. For previous versions it contained a bug, which is now corrected to return the same information.

**Comment by ddemeyer** [comment]
@ArianArt  Please close #177 (this) and origin story #171 if PR is merged, tested and Release notes are adapted.
