### ISSUE TITLE
Get-IshTypeFieldDefinition returns Event progress and detail column DATETIMEKIND

### ISSUE THREAD

**Issue by ArianArt** [RWS/ISHRemote#191]
Overall this ticket should make sure that pre-15.1.0 (before User DisplayName) should return the same as 15.1.0 (where FieldSetup API call adds Events and BackgroundTask).
- [x] DATETIMEKIND fields are removed from the ISHEvent FieldDefinitions and pester tests are aligned accordingly.
- [x] ``Compare-IshTypeFieldDefinition -LeftIshSession $ishSession1404 -RightIshSession $ishSession1501 -IncludeIdentical | Out-GridView`` compare an 14.0.4/15.0.0 to 15.1.0 should highlight the table changes of BackgroundTask and Events that happened to cover 15.1's introduction of User DisplayName
- [x] Matching Pester Tests

**Comment by ddemeyer** [comment]
Similar change to #185 ... just making Pester test count match up with actual count from soon-to-be-released Tridion Docs 15.1/15.1.0
